export { calcularLiquidacion } from './calculators/liquidacion'
export { calcularCTS } from './calculators/cts'
export { calcularGratificacion } from './calculators/gratificacion'
export { calcularIndemnizacion } from './calculators/indemnizacion'
export { calcularHorasExtras } from './calculators/horas-extras'
export { calcularVacaciones } from './calculators/vacaciones'
export { calcularMultaSunafil } from './calculators/multa-sunafil'
export type { MultaSunafilInput, MultaSunafilResult } from './calculators/multa-sunafil'
export { calcularInteresesLegales } from './calculators/intereses-legales'
export type { InteresesLegalesInput, InteresesLegalesResult } from './calculators/intereses-legales'
export { calcularAportesPrevisionales, compararAfpVsOnp } from './calculators/aportes-previsionales'
export type { AportesInput, AportesResult } from './calculators/aportes-previsionales'
export { calcularUtilidades } from './calculators/utilidades'
export type { UtilidadesInput, UtilidadesResult, TrabajadorUtilidades, DetalleTrabajadorUtilidades } from './calculators/utilidades'
export { PERU_LABOR, calcularPeriodoLaboral, calcularRemuneracionComputable } from './peru-labor'
export type * from './types'
