export const workerAuthAppearance = {
  variables: {
    colorPrimary: '#059669',
    colorText: '#0f172a',
    colorTextSecondary: '#475569',
    colorBackground: '#ffffff',
    colorInputBackground: '#ffffff',
    colorInputText: '#0f172a',
    borderRadius: '14px',
    fontFamily: 'var(--font-jakarta), var(--font-geist-sans), sans-serif',
  },
  elements: {
    rootBox: 'mx-auto !w-full !max-w-full !min-w-0',
    cardBox: '!w-full !max-w-full !min-w-0',
    card: '!w-full !max-w-full !min-w-0 !rounded-[24px] !border !border-[#e2e8f0] !bg-[#ffffff] !p-6 !shadow-none',
    main: '!w-full !max-w-full !min-w-0',
    form: '!w-full !max-w-full !min-w-0',
    header: 'hidden',
    headerTitle: 'hidden',
    headerSubtitle: 'hidden',
    socialButtonsBlockButton:
      '!h-11 !rounded-xl !border !border-[#cbd5e1] !bg-[#ffffff] !text-[#0f172a] hover:!bg-[#f8fafc]',
    socialButtonsBlockButtonText: '!text-sm !font-semibold !text-[#0f172a]',
    dividerLine: '!bg-[#cbd5e1]',
    dividerText: '!text-xs !font-semibold !uppercase !tracking-widest !text-[#64748b]',
    formFieldLabel: '!text-sm !font-semibold !text-[#334155]',
    formFieldInput:
      '!h-11 !rounded-xl !border !border-[#cbd5e1] !bg-[#ffffff] !px-3 !text-base !font-medium !text-[#0f172a] placeholder:!text-[#64748b] focus:!border-[#059669] focus:!ring-4 focus:!ring-[#d1fae5]',
    formFieldInputShowPasswordButton: '!text-[#64748b] hover:!text-[#0f172a]',
    formButtonPrimary:
      '!h-11 !rounded-xl !bg-[#0d9488] !text-sm !font-bold !text-[#ffffff] !shadow-lg !shadow-emerald-600/20 hover:!bg-[#0f766e]',
    footer: '!border-t !border-[#e2e8f0] !bg-[#ffffff]',
    footerAction: '!text-sm !text-[#475569]',
    footerActionLink: '!font-bold !text-[#047857] hover:!text-[#065f46]',
    identityPreview: '!rounded-xl !border !border-[#e2e8f0] !bg-[#f8fafc]',
    identityPreviewText: '!text-[#0f172a]',
    identityPreviewEditButton: '!font-semibold !text-[#047857]',
    formResendCodeLink: '!font-semibold !text-[#047857]',
    formFieldErrorText: '!text-sm !font-semibold !text-red-600',
    alert: '!rounded-xl !border !border-[#fecaca] !bg-[#fef2f2] !text-[#b91c1c]',
  },
} as const
