-- Fase 2 — Sistema de constancias del cliente para auto-derivación SUNAFIL

-- Agregar nuevos valores al enum OrgDocType
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'SCTR_POLIZA';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'REMYPE_CONSTANCIA';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'CTS_DEPOSITO_CONSTANCIA';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'AFP_PAGO_CONSTANCIA';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'ONP_PAGO_CONSTANCIA';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'ESSALUD_PAGO_CONSTANCIA';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'PLAME_CONFIRMACION';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'DJ_UTILIDADES';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'INFORME_LAB_FISICO';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'INFORME_LAB_QUIMICO';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'INFORME_LAB_BIOLOGICO';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'INFORME_LAB_ERGONOMICO';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'INFORME_LAB_PSICOSOCIAL';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'ACTA_SIMULACRO_EVACUACION';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'ACTA_COMITE_SST_MENSUAL';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'INFORME_ANUAL_HOSTIGAMIENTO_MTPE';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'CONVENIO_PRACTICAS_REGISTRADO_MTPE';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'AUTORIZACION_MTPE_EXTRANJERO';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'REGISTRO_SUNAFIL_TERCERIZADORA';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'CONSTANCIA_SEGURO_VIDA_LEY';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'CUADRO_CATEGORIAS_LEY_30709';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'MAPA_RIESGOS_ACTUALIZADO';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'POLITICA_SST';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'T_REGISTRO_CONSTANCIA_ALTA';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'T_REGISTRO_CONSTANCIA_BAJA';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'SINTESIS_LEGISLACION_LABORAL';
ALTER TYPE "OrgDocType" ADD VALUE IF NOT EXISTS 'REPORTE_HIGIENE_INSTALACIONES';

-- CreateTable: DocumentRequirement
CREATE TABLE "document_requirements" (
  "id" TEXT NOT NULL,
  "org_id" TEXT NOT NULL,
  "document_type" "OrgDocType" NOT NULL,
  "is_required" BOOLEAN NOT NULL DEFAULT true,
  "renewal_frequency_days" INTEGER,
  "criticality" TEXT NOT NULL DEFAULT 'MEDIUM',
  "applies_to_regimen" TEXT[] DEFAULT ARRAY[]::TEXT[],
  "applies_to_sector" TEXT,
  "help_text" TEXT,
  "base_legal" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "document_requirements_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "document_requirements_org_id_document_type_key" ON "document_requirements"("org_id", "document_type");

-- CreateIndex
CREATE INDEX "document_requirements_org_id_idx" ON "document_requirements"("org_id");

-- AddForeignKey
ALTER TABLE "document_requirements" ADD CONSTRAINT "document_requirements_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
