ALTER TYPE "OrgStructureChangeType" ADD VALUE IF NOT EXISTS 'DRAFT_CREATE';
ALTER TYPE "OrgStructureChangeType" ADD VALUE IF NOT EXISTS 'DRAFT_UPDATE';
ALTER TYPE "OrgStructureChangeType" ADD VALUE IF NOT EXISTS 'DRAFT_APPLY';
ALTER TYPE "OrgStructureChangeType" ADD VALUE IF NOT EXISTS 'DRAFT_DISCARD';
